### ISSUE TITLE
Kernel compilation failed (configuration multimedia support on module instead of builded in)

### ISSUE THREAD

**Issue by VivienLaure** [BPI-SINOVOIP/BPI-R2-bsp#32]
Hi, 

I wanted to change a little bit the configuration of the kernel so that i can use a camera with my BPI-R2.
 
My setup is particular since i use a grabber (the Magewell USB Capture HDMI Gen 2) and a camera plugged in hdmi to this grabber. Finally the camera should be seen as an usb camera device. 

The setup is working on my ubuntu 16.04 (kernel 4.13.0-39-generic), i use uvc and v4l and i can display the camera flux using qv4l2 for example. 

I tried to configure the kernel so that i have the same modules i use on my desktop version. To do so i had to configure MEDIA_CAMERA_SUPPORT = y, MEDIA_USB_SUPPORT = y and USB_VIDEO_CLASS = m. 

The list of module i need : 

Module                        Size           Used by
snd_usb_audio           196608      1
snd_usbmidi_lib          32768        1 snd_usb_audio
uvcvideo                      90112        0
videobuf2_vmalloc      16384        1  uvcvideo
videobuf2_memops    16384        1 videobuf2_vmalloc
videobuf2_v4l2            24576       1 uvcvideo
videobuf2_core           40960        2 uvcvideo,videobuf2_v4l2

videodev                     176128      3 uvcvideo,videobuf2_core,videobuf2_v4l2
media                          40960       2 uvcvideo,videodev

The two module i'm missing are media.ko and videodev.ko but when i set MEDIA_SUPPORT = m , i got the following error at the compilation (see attached file). I don't understand this error because i found the definition of the functions marked as undefined references in linux-mt/include/media/cec.h. 

I don't know if i'm missing dependencies or if it's a bug because i'm pretty new to that stuff, a little help would be appreciated. 

If you need futher information don't hesitate. 

Vivien LAURE

[Error_log.txt](https://github.com/BPI-SINOVOIP/BPI-R2-bsp/files/1951219/Error_log.txt)
